namespace: microservices

frontend:
  image: ranjakube/signoz-frontend:v1
  replicas: 2

backend:
  image: ranjakube/signoz-backend:v1
  replicas: 2

  env:
    POSTGRES_HOST: postgres

postgres:
  image: postgres:15
  storage: 2Gi

ingress:
  host: myapp.local
